# Generated by Django 2.2.3 on 2019-07-24 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import planner.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('time_wake', models.TimeField()),
                ('time_sleep', models.TimeField()),
                ('time_work_start', models.TimeField()),
                ('time_work_end', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=10000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[(planner.models.TaskStatus('Not Done'), 'Not Done'), (planner.models.TaskStatus('In Progress'), 'In Progress'), (planner.models.TaskStatus('Complete'), 'Complete')], max_length=5)),
                ('priority', models.CharField(choices=[(planner.models.TaskPriority('Low'), 'Low'), (planner.models.TaskPriority('Normal'), 'Normal'), (planner.models.TaskPriority('High'), 'High'), (planner.models.TaskPriority('Critical'), 'Critical')], max_length=8)),
                ('category', models.CharField(choices=[(planner.models.TaskCategory('Home'), 'Home'), (planner.models.TaskCategory('Work'), 'Work'), (planner.models.TaskCategory('Other'), 'Other')], max_length=5)),
                ('date_due', models.DateTimeField(blank=True)),
                ('time_estimate', models.DurationField(blank=True)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_assigned', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
